
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldpajuiackqmadfigmoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkcGFqdWlhY2txbWFkZmlnbW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDg0MDQsImV4cCI6MjA2MTg4NDQwNH0.noLJK-A8P2TaFI_1Jxt5UvhNQ1dBcytNgPsiijps2cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the typed client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});

// Type augmentation for the RPC functions that aren't in the auto-generated types
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database = any> {
    rpc<
      FunctionName extends 'add_task_reward' | 'add_referral_bonus' | 'create_admin_user',
      Args extends
        FunctionName extends 'add_task_reward' ? { user_addr: string; task_id: string } :
        FunctionName extends 'add_referral_bonus' ? { referrer_addr: string; bonus_amount: number } :
        Record<PropertyKey, never>
    >(
      functionName: FunctionName,
      args: Args,
      options?: { count?: 'exact' | 'planned' | 'estimated' }
    ): Promise<{ data: any; error: Error | null }>;
  }
}
